# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    paths:
      - 'CHANGELOG.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [ push-image ]
    steps:
      - name: Deploy Docker Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          command_timeout: 10m
          script: |
            cd /opt/flexmodel-quickstarts/docker-compose
            docker-compose pull
            docker-compose up -d
