# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy Preview Website

on:
  push:
    branches: [ "main" ]
    paths:
      - 'CHANGELOG.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Docker Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          command_timeout: 10m
          script: |
            cd /opt/flexmodel-quickstarts/docker-compose
            docker-compose pull
            docker-compose up -d
